### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by yaralahruthik** [Frontend-Hire/fh-portfolio-template#1]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the current portfolio template lacks a dark mode option, which makes it difficult to use in low-light environments.

**Describe the solution you'd like**
Implement a dark mode option in the portfolio template, where users can toggle between light and dark themes. This would make the template more user-friendly, especially for those who prefer working in darker environments.

**Describe alternatives you've considered**
I've considered using third-party browser extensions to apply a dark theme to the template, but this is not as seamless or well-integrated as having native dark mode support.

**Additional context**
Dark mode has become a standard across many websites and applications, as it reduces eye strain and enhances accessibility for users in low-light settings. Adding dark mode would also increase the attractiveness of the template for developers who prefer dark-themed UIs.

**Comment by NitanJana** [comment]
working on this.
