### ISSUE TITLE
OpenGraph Image for Blogs and Learnings

### ISSUE THREAD

**Issue by yaralahruthik** [Frontend-Hire/fh-portfolio-template#2]
**Is your feature request related to a problem? Please describe.**
Currently, there’s no OpenGraph (OG) image support for the blog and learning sections, which results in plain or generic previews when shared on social media platforms.

**Describe the solution you'd like**
Add OpenGraph metadata support to automatically generate or allow custom OG images for blogs and learning pages. This will improve the appearance and engagement of shared links on platforms like Twitter, LinkedIn, and Facebook by providing a rich visual preview.

**Describe alternatives you've considered**
Another option is manually adding images when sharing links, but this is cumbersome and does not ensure a consistent or optimized appearance.

**Additional context**
OpenGraph images are crucial for social media sharing as they make links more visually appealing and clickable. Adding this feature can improve the overall user experience and engagement for anyone sharing content from the portfolio template.

**Comment by suyash5641** [comment]
Hello @yaralahruthik I am currently working on this issue . 
Thanks
