### ISSUE TITLE
Improve Documentation to Differentiate Use Cases for Blogs and Learnings

### ISSUE THREAD

**Issue by yaralahruthik** [Frontend-Hire/fh-portfolio-template#3]
**Is your feature request related to a problem? Please describe.**
The current documentation does not clearly explain the difference between the "Blogs" and "Learnings" sections, leading to confusion among users about when to use each section. This lack of clarity may result in inconsistent or improper content placement.

**Describe the solution you'd like**
Enhance the documentation to include detailed use cases for the "Blogs" and "Learnings" sections. Clearly explain what type of content belongs in each section, with examples to guide users on how to categorize their posts appropriately.

**Describe alternatives you've considered**
Without clear documentation, users may create their own interpretation of how to use these sections, which could lead to misclassification. I considered looking at the source code to understand the differences, but this is not practical for most users.

**Additional context**
- "Blogs" could be positioned as a place for longer-form, more in-depth articles on various topics.
- "Learnings" might be ideal for shorter, more frequent updates or personal development insights.

Including examples in the documentation would help streamline the process and improve the user experience by ensuring that content is consistently categorized.

**Comment by mariamsamaha** [comment]
Hello @yaralahruthik,I would love to work on this issue.could you please assign it to me? thanks in advance

**Comment by mariamsamaha** [comment]
@yaralahruthik Thank you for giving me the opportunity to contribute to this issue,could you please review the changes and let me know if any additional adjustments are needed.I would appreciate it a lot

**Comment by yaralahruthik** [comment]
@mariamsamaha Thanks for working on this issue!
