### ISSUE TITLE
Implement View Transitions for Smoother Navigation in Blogs and Learnings

### ISSUE THREAD

**Issue by yaralahruthik** [Frontend-Hire/fh-portfolio-template#4]
**Is your feature request related to a problem? Please describe.**
The current navigation between the "Blogs" and "Learnings" sections lacks smooth transitions, leading to a disjointed user experience. This makes the interface feel less polished and reduces the overall engagement when moving between different content sections.

**Describe the solution you'd like**
Implement View Transitions API or similar smooth transition animations between the "Blogs" and "Learnings" sections. This would make the UI feel more dynamic and responsive, creating a seamless experience when users navigate between different pages.

**Describe alternatives you've considered**
An alternative would be to keep the current static transitions, but this doesn’t provide the same level of modern, interactive experience that users expect in web applications today.

**Additional context**
- View Transitions would enhance the user experience by making the interface feel more fluid and interactive.
- This feature can also help improve the perceived speed of the site, as users will see immediate visual feedback during navigation.
- It aligns with modern UI/UX best practices, providing a smoother experience, especially for users who frequently switch between content sections.

**Comment by bhanuteja-03** [comment]
https://github.com/user-attachments/assets/8ed0c99e-e03b-4159-a511-3b3157aeb9be

@yaralahruthik I have done above transitions using View transitions, let me know if it is okay so that I will raise the PR

**Comment by yaralahruthik** [comment]
> 
> https://github.com/user-attachments/assets/8ed0c99e-e03b-4159-a511-3b3157aeb9be
> 
> @yaralahruthik I have done above transitions using View transitions, let me know if it is okay so that I will raise the PR

This looks perfect! Go ahead.
